# Generated by Django 3.2 on 2023-01-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_coins_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coins',
            options={'verbose_name_plural': 'Coins'},
        ),
    ]
