# Generated by Django 3.2 on 2023-01-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_alter_coins_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
