# Generated by Django 3.2 on 2023-01-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_alter_coins_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
