# Generated by Django 3.2 on 2023-01-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('metal', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('ask_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('negotiable', models.BooleanField(default=False)),
                ('condition', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Sell',
            },
        ),
    ]
