# Generated by Django 3.2 on 2023-01-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_alter_sell_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
